test_tup1 = (1, 3, 5) 
test_tup2 = (7, 9) 
print("\n")
print("The original tuple 1 : " + str(test_tup1)) 
print("The original tuple 2 : " + str(test_tup2)) 
res = sum((test_tup1, test_tup2), ()) 
print("The tuple after concatenation is : " + str(res))
print("\n")
